#version: '3'

services:
  # Run one of these two Astro services at a time by specifying it directly with the command
  # e.g., docker-compose up astro-dev astro-prod

  # Astro Development Server
  slidev-dev:
    image: node:22.16-alpine3.22 #node:18-alpine
    container_name: astro-dev
    working_dir: /app
    ports:
      - "3030:3030"  # Astro dev server with live changes port - Go to http://localhost:4324/
    volumes:
      - /home/jalcocert/Desktop/slidev/slidevsample:/app #this is a common volume for Astro container to place the .md post
    command: sh -c "cd /app && npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - project-network
    tty: true
    restart: "no"

  slidev-prod:
    build: .
    container_name: astro-prod
    working_dir: /app
    ports:
      - "8087:3030"  # Serve Slidev on port 3030 for consistency
    environment:
      - NODE_ENV=production
    networks:
      - project-network
      #- cloudflared_tunnel
    restart: "no"

networks:
  project-network:
    name: project-documentation-network

#networks:
  # cloudflared_tunnel:
  #   external: true