name: Deploy Slidev site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          cd ./slidevsample
          npm install
      - name: Build Slidev project
        run: |
          cd ./slidevsample
          npm install -g @slidev/cli #npm install --save-dev @slidev/cli
          npm i -D playwright-chromium
          slidev build --base /slidev/ 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./slidevsample/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

# name: Deploy Slidev site to Pages

# on:
#   push:
#     branches: ["main"]
#   workflow_dispatch:

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

# defaults:
#   run:
#     shell: bash

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       NODE_VERSION: 20
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 
#       - name: Install Slidev CLI
#         run: npm install -g @slidev/cli
#       - name: Install dependencies and build
#         run: |
#           npm install
#           slidev build --base /slidev/
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v2
#         with:
#           path: ./dist

#   deploy:
#     environment:
#       name: github-pages
#       url: 
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v2